algoritmo "Orientação a objeto"

tipo

cadastroCliente = registro
   nome: caractere
   rg: caractere
   idade: inteiro
fimregistro

Var

cliente1: cadastroCliente

inicio

Escreva ("Digite seu nome: ")
leia (cliente1.nome)

Escreva ("Digite seu rg: ")
leia (cliente1.rg)

Escreva ("Digite sua idade: ")
leia (cliente1.idade)

Escreval ("")
Escreval ("Nome: ", cliente1.nome)
Escreval ("Rg: ", cliente1.rg)
Escreval ("Idade: ", cliente1.idade)

fimalgoritmo